import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
	en: {
		language: 'Language',
		findWork: 'Find work',
		logIn: 'Log in',
		getStarted: 'Get started',
		savedJobs: 'Saved jobs',
		myApplications: 'My applications',
		profile: 'Profile',
		myPostings: 'My postings',
		postJob: 'Post a job',
		companyProfile: 'Company profile',
		logOut: 'Log out',
		closeMenu: 'Close menu',
		openMenu: 'Open menu',
		logOutTitle: 'Log out?',
		logOutDescription: 'Are you sure you want to log out of your account?',
		cancel: 'Cancel',
		backToJobs: 'Back to all jobs',
		allJobs: 'All jobs',
		email: 'Email',
		password: 'Password',
		welcomeBack: 'Welcome back',
		loginDescription: 'Log in to keep track of your search.',
		loggingIn: 'Logging in...',
		forgotPassword: 'Forgot your password?',
		resetItHere: 'Reset it here',
		newHere: 'New here?',
		createAccount: 'Create an account',
		joinServease: 'Join Servease',
		registerDescription: 'Set up an account as a candidate or an employer.',
		lookingForWork: "I'm looking for work",
		hiring: "I'm hiring",
		fullName: 'Full name',
		companyName: 'Company name',
		confirmPassword: 'Confirm password',
		creatingAccount: 'Creating account...',
		alreadyHaveAccount: 'Already have an account?',
		checkEmail: 'Check your email',
		verificationSent: "We've sent a verification link to",
		verifyBeforeLogin: 'Please verify your email before logging in.',
		goToLogin: 'Go to login',
		resetPassword: 'Reset your password',
		resetDescription: "Enter your email and we'll send a secure reset link.",
		sendingLink: 'Sending link...',
		sendResetLink: 'Send reset link',
		resetEmailSent: 'We have emailed your password reset link.',
		rememberedIt: 'Remembered it?',
		backToLogin: 'Back to login',
		invalidResetLink: 'Invalid reset link',
		invalidResetDescription:
			'The reset link is missing required details. Please request a new one.',
		requestNewResetLink: 'Request a new reset link',
		chooseNewPassword: 'Choose a new password',
		newPasswordDescription: 'Create a password with at least 8 characters.',
		newPassword: 'New password',
		resettingPassword: 'Resetting password...',
		resetPasswordButton: 'Reset password',
		passwordReset: 'Your password has been reset.',
		verificationFailed: 'Verification failed',
		verificationInvalid: 'This verification link is invalid or has expired.',
		verifyingEmail: 'Verifying your email...',
		oneMoment: 'One moment please.',
		accountSettings: 'Account settings',
		accountSettingsDescription:
			'Manage the email address and password used to sign in.',
		emailAddress: 'Email address',
		currentPassword: 'Current password',
		confirmNewPassword: 'Confirm new password',
		saving: 'Saving...',
		saveAccountSettings: 'Save account settings',
		accountSettingsUpdated: 'Account settings updated.',
		deleteAccount: 'Delete account',
		deleteAccountDescription:
			'Deleting your account permanently removes your profile, job posts, applications, and saved jobs. This cannot be undone.',
		deleteMyAccount: 'Delete my account',
		finalDeleteConfirmation:
			'Final confirmation: type DELETE and enter your current password to permanently remove this account.',
		typeDelete: 'Type DELETE to confirm',
		deletingAccount: 'Deleting account...',
		permanentlyDelete: 'Permanently delete account',
		jobTitle: 'Job title',
		description: 'Description',
		requirementsOptional: 'Requirements (optional)',
		skillsCommaSeparated: 'Skills (comma-separated)',
		employmentType: 'Employment type',
		workMode: 'Work mode',
		salaryMin: 'Salary min',
		salaryMax: 'Salary max',
		currency: 'Currency',
		status: 'Status',
		draftHidden: 'Draft (hidden from search)',
		openAccepting: 'Open (accepting applications)',
		closed: 'Closed',
		publishPosting: 'Publish posting',
		saveChanges: 'Save changes',
		postingSaved: 'Could not save this posting.',
		postJobDescription:
			'Fill in the details candidates will see on the listing.',
		couldNotPublish: 'Could not publish this posting.',
		editPosting: 'Edit posting',
		postingNotFound: 'Posting not found.',
		couldNotUpdate: 'Could not update this posting.',
		openingPosting: 'Opening posting...',
		postingGone: "This posting isn't here anymore.",
		aboutRole: 'About the role',
		whatLookingFor: "What they're looking for",
		applyRole: 'Apply to this role',
		coverLetterOptional: 'Cover letter (optional)',
		resumeOptional: 'Resume (PDF or Word, optional)',
		coverLetterPlaceholder: 'Why this role, and why you.',
		profileResumeUsed:
			"The resume on your profile will be used if you don't attach one.",
		removeSavedJob: 'Remove saved job',
		saveJob: 'Save job',
		submitApplication: 'Submit application',
		sending: 'Sending...',
		applicationSent:
			'Application sent. The employer can now see it on their end.',
		loginToApply: 'Log in as a candidate to apply.',
		viewApplicants: 'View applicants',
		yourApplications: 'Your applications',
		trackStatus: 'Track where things stand.',
		editProfile: 'Edit profile',
		noApplications: 'No applications yet.',
		browseOpenRoles: 'Browse open roles',
		withdraw: 'Withdraw',
		withdrawConfirm: 'Withdraw this application?',
		yourPostings: 'Your postings',
		manageJobs: 'Manage jobs and review applicants.',
		emptyPostings: "You haven't posted any jobs yet.",
		salaryNotListed: 'Salary not listed',
		applicant: 'applicant',
		applicants: 'Applicants',
		edit: 'Edit',
		delete: 'Delete',
		deletePostingConfirm: 'Delete this posting? This cannot be undone.',
		companyProfileDescription:
			'Candidates see this on your job postings and company page.',
		website: 'Website',
		industry: 'Industry',
		companySize: 'Company size',
		logo: 'Logo',
		saveCompanyProfile: 'Save company profile',
		companyProfileUpdated: 'Company profile updated.',
		candidateProfile: 'Your profile',
		candidateProfileDescription: 'This is what employers see when you apply.',
		headline: 'Headline',
		bio: 'Bio',
		yearsExperience: 'Years of experience',
		linkedinUrl: 'LinkedIn URL',
		portfolioUrl: 'Portfolio URL',
		resume: 'Resume (PDF or Word)',
		resumeOnFile: 'A resume is already on file.',
		saveProfile: 'Save profile',
		savingProfile: 'Saving profile',
		profileUpdated: 'Profile updated.',
		applicationDetails: 'Application details',
		submitted: 'Submitted',
		coverLetter: 'Cover letter',
		downloadResume: 'Download resume',
		noResume: 'No resume attached',
		noCoverLetter: 'No cover letter was included.',
		viewJobPosting: 'View job posting',
		appNotFound: 'Application not found.',
		filterApplicants: 'Filter applicants by status',
		allStatuses: 'All statuses',
		pending: 'Pending',
		reviewed: 'Reviewed',
		shortlisted: 'Shortlisted',
		rejected: 'Rejected',
		hired: 'Hired',
		noApplicants: 'No applicants match this filter yet.',
		updateHiringStatus: 'Update hiring status',
		collapseApplicant: 'Collapse applicant details',
		expandApplicant: 'Expand applicant details',
		nothingHere: "There's nothing at this address.",
		previous: 'Previous',
		next: 'Next',
		pageOf: 'Page {current} of {last}',
		loading: 'Loading...',
		loadingPage: 'Loading page',
		somethingWrong: 'Something went wrong',
		refreshTryAgain: 'Please refresh the page and try again.',
		refreshPage: 'Refresh page',
		switchLightTheme: 'Switch to light theme',
		switchDarkTheme: 'Switch to dark theme',
		reviewCandidates: 'Review candidates and update their hiring status.',
		couldNotLogin: 'Could not log in.',
		couldNotCreateAccount: 'Could not create your account.',
		couldNotSendReset: 'Could not send reset email.',
		couldNotReset: 'Could not reset your password.',
		couldNotUpdateAccount: 'Could not update account settings.',
		couldNotDeleteAccount: 'Could not delete your account. Please try again.',
		couldNotSubmitApplication: 'Could not submit your application.',
		updateListingDescription: 'Update the listing candidates see.',
		savedJobsDescription: "Roles you've bookmarked to revisit.",
		nothingSaved: 'Nothing saved yet.',
		couldNotDownloadResume: 'Could not download resume.',
		couldNotSaveProfile: 'Could not save your profile.',
		couldNotSaveCompanyProfile: 'Could not save your company profile.',
		openToNewRoles: 'Open to new roles',
		skills: 'Skills',
		companyFallback: 'A company',
		timeUnits: {
			year: 'year',
			month: 'month',
			week: 'week',
			day: 'day',
			hour: 'hour',
			minute: 'minute',
			plural: {
				year: 'years',
				month: 'months',
				week: 'weeks',
				day: 'days',
				hour: 'hours',
				minute: 'minutes',
			},
			justNow: 'just now',
			ago: 'ago',
		},
		open: 'Open',
		draft: 'Draft',
		pendingReview: 'Pending review',
		notSelected: 'Not selected',
		servingLocation: 'Serving Quezon, Palawan',
		homeTitle: 'Find the right job. Hire the right person.',
		homeDescription:
			'Servease connects people in Quezon, Palawan with local opportunities and trusted candidates.',
		serviceOrKeyword: 'Service or keyword',
		location: 'Location',
		anyType: 'Any type',
		fullTime: 'Full-time',
		partTime: 'Part-time',
		contract: 'Contract',
		internship: 'Internship',
		temporary: 'Temporary',
		anyMode: 'Any mode',
		onSite: 'On-site',
		remote: 'Remote',
		hybrid: 'Hybrid',
		findJobs: 'Find jobs',
		fetchingListings: 'Fetching listings...',
		listingsLoadError: 'Could not load listings right now.',
		noRoles: 'No roles match those filters yet. Try widening your search.',
		footer: 'Servease - find your next move, make it count',
		pageTitles: {
			home: 'Find Your Next Gig',
			login: 'Welcome Back',
			register: 'Join the Crew',
			forgotPassword: 'Forgot Your Password',
			resetPassword: 'Reset Your Password',
			dashboard: 'Your Workspace',
			postJob: 'Post a New Opportunity',
			savedJobs: 'Your Saved Roles',
			companyProfile: 'Company Profile',
			candidateProfile: 'Candidate Profile',
			jobDetails: 'Job Details',
			editJob: 'Edit Job',
			applicants: 'Applicants',
			applicationDetails: 'Application Details',
			pageNotFound: 'Page Not Found',
			page: 'Page',
			accountSettings: 'Account settings',
		},
	},
	fil: {
		language: 'Wika',
		findWork: 'Maghanap ng trabaho',
		logIn: 'Mag-log in',
		getStarted: 'Magsimula',
		savedJobs: 'Nai-save na trabaho',
		myApplications: 'Aking mga aplikasyon',
		profile: 'Profile',
		myPostings: 'Aking mga post',
		postJob: 'Mag-post ng trabaho',
		companyProfile: 'Profile ng kumpanya',
		logOut: 'Mag-log out',
		closeMenu: 'Isara ang menu',
		openMenu: 'Buksan ang menu',
		logOutTitle: 'Mag-log out?',
		logOutDescription:
			'Sigurado ka bang gusto mong mag-log out sa iyong account?',
		cancel: 'Kanselahin',
		backToJobs: 'Bumalik sa lahat ng trabaho',
		allJobs: 'Lahat ng trabaho',
		email: 'Email',
		password: 'Password',
		welcomeBack: 'Maligayang pagbabalik',
		loginDescription: 'Mag-log in para masubaybayan ang iyong paghahanap.',
		loggingIn: 'Nagla-log in...',
		forgotPassword: 'Nakalimutan ang password?',
		resetItHere: 'I-reset dito',
		newHere: 'Bago dito?',
		createAccount: 'Gumawa ng account',
		joinServease: 'Sumali sa Servease',
		registerDescription: 'Gumawa ng account bilang kandidato o employer.',
		lookingForWork: 'Naghahanap ako ng trabaho',
		hiring: 'Naghahanap ako ng empleyado',
		fullName: 'Buong pangalan',
		companyName: 'Pangalan ng kumpanya',
		confirmPassword: 'Kumpirmahin ang password',
		creatingAccount: 'Ginagawa ang account...',
		alreadyHaveAccount: 'May account ka na?',
		checkEmail: 'Suriin ang iyong email',
		verificationSent: 'Nagpadala kami ng verification link sa',
		verifyBeforeLogin: 'I-verify ang iyong email bago mag-log in.',
		goToLogin: 'Pumunta sa login',
		resetPassword: 'I-reset ang iyong password',
		resetDescription:
			'Ilagay ang iyong email at magpapadala kami ng secure na reset link.',
		sendingLink: 'Ipinapadala ang link...',
		sendResetLink: 'Ipadala ang reset link',
		resetEmailSent:
			'Naipadala na namin ang password reset link sa iyong email.',
		rememberedIt: 'Naalala mo na?',
		backToLogin: 'Bumalik sa login',
		invalidResetLink: 'Hindi wastong reset link',
		invalidResetDescription:
			'Kulang ang kinakailangang detalye sa reset link. Humiling ng bago.',
		requestNewResetLink: 'Humiling ng bagong reset link',
		chooseNewPassword: 'Pumili ng bagong password',
		newPasswordDescription:
			'Gumawa ng password na may hindi bababa sa 8 character.',
		newPassword: 'Bagong password',
		resettingPassword: 'Nire-reset ang password...',
		resetPasswordButton: 'I-reset ang password',
		passwordReset: 'Na-reset na ang iyong password.',
		verificationFailed: 'Hindi nagtagumpay ang verification',
		verificationInvalid: 'Hindi wasto o paso na ang verification link.',
		verifyingEmail: 'Bine-verify ang iyong email...',
		oneMoment: 'Sandali lamang.',
		accountSettings: 'Mga setting ng account',
		accountSettingsDescription:
			'Pamahalaan ang email at password na ginagamit sa pag-sign in.',
		emailAddress: 'Email address',
		currentPassword: 'Kasalukuyang password',
		confirmNewPassword: 'Kumpirmahin ang bagong password',
		saving: 'Sine-save...',
		saveAccountSettings: 'I-save ang mga setting ng account',
		accountSettingsUpdated: 'Na-update ang mga setting ng account.',
		deleteAccount: 'Tanggalin ang account',
		deleteAccountDescription:
			'Permanenteng tatanggalin ng pag-delete ang iyong profile, job post, aplikasyon, at nai-save na trabaho. Hindi na ito maibabalik.',
		deleteMyAccount: 'Tanggalin ang aking account',
		finalDeleteConfirmation:
			'Huling kumpirmasyon: i-type ang DELETE at ilagay ang iyong kasalukuyang password para permanenteng tanggalin ang account.',
		typeDelete: 'I-type ang DELETE para kumpirmahin',
		deletingAccount: 'Tine-delete ang account...',
		permanentlyDelete: 'Permanenteng tanggalin ang account',
		jobTitle: 'Pamagat ng trabaho',
		description: 'Paglalarawan',
		requirementsOptional: 'Mga requirement (opsyonal)',
		skillsCommaSeparated: 'Mga kasanayan (pinaghihiwalay ng kuwit)',
		employmentType: 'Uri ng trabaho',
		workMode: 'Paraan ng trabaho',
		salaryMin: 'Minimum na sahod',
		salaryMax: 'Maximum na sahod',
		currency: 'Currency',
		status: 'Status',
		draftHidden: 'Draft (hindi makikita sa paghahanap)',
		openAccepting: 'Bukas (tumatanggap ng aplikasyon)',
		closed: 'Sarado',
		publishPosting: 'I-publish ang post',
		saveChanges: 'I-save ang mga pagbabago',
		postingSaved: 'Hindi ma-save ang job post.',
		postJobDescription:
			'Ilagay ang mga detalye na makikita ng mga kandidato sa listing.',
		couldNotPublish: 'Hindi ma-publish ang job post.',
		editPosting: 'I-edit ang post',
		postingNotFound: 'Hindi nahanap ang job post.',
		couldNotUpdate: 'Hindi ma-update ang job post.',
		openingPosting: 'Binubuksan ang post...',
		postingGone: 'Wala na ang job post na ito.',
		aboutRole: 'Tungkol sa trabaho',
		whatLookingFor: 'Mga hinahanap nila',
		applyRole: 'Mag-apply sa trabahong ito',
		coverLetterOptional: 'Cover letter (opsyonal)',
		resumeOptional: 'Resume (PDF o Word, opsyonal)',
		coverLetterPlaceholder: 'Bakit ang trabahong ito, at bakit ikaw?',
		profileResumeUsed:
			'Gagamitin ang resume sa iyong profile kung hindi ka mag-attach ng bago.',
		removeSavedJob: 'Alisin sa nai-save',
		saveJob: 'I-save ang trabaho',
		submitApplication: 'Ipadala ang aplikasyon',
		sending: 'Ipinapadala...',
		applicationSent: 'Naipadala ang aplikasyon. Makikita na ito ng employer.',
		loginToApply: 'Mag-log in bilang kandidato para mag-apply.',
		viewApplicants: 'Tingnan ang mga aplikante',
		yourApplications: 'Iyong mga aplikasyon',
		trackStatus: 'Subaybayan ang status ng mga ito.',
		editProfile: 'I-edit ang profile',
		noApplications: 'Wala pang aplikasyon.',
		browseOpenRoles: 'Tingnan ang mga bukas na trabaho',
		withdraw: 'Bawiin',
		withdrawConfirm: 'Bawiin ang aplikasyon na ito?',
		yourPostings: 'Iyong mga post',
		manageJobs: 'Pamahalaan ang mga trabaho at tingnan ang mga aplikante.',
		emptyPostings: 'Wala ka pang nai-post na trabaho.',
		salaryNotListed: 'Walang nakalistang sahod',
		applicant: 'aplikante',
		applicants: 'Mga aplikante',
		edit: 'I-edit',
		delete: 'Tanggalin',
		deletePostingConfirm: 'Tanggalin ang job post? Hindi na ito maibabalik.',
		companyProfileDescription:
			'Makikita ito ng mga kandidato sa iyong job post at company page.',
		website: 'Website',
		industry: 'Industriya',
		companySize: 'Laki ng kumpanya',
		logo: 'Logo',
		saveCompanyProfile: 'I-save ang profile ng kumpanya',
		companyProfileUpdated: 'Na-update ang profile ng kumpanya.',
		candidateProfile: 'Iyong profile',
		candidateProfileDescription:
			'Ito ang makikita ng mga employer kapag nag-apply ka.',
		headline: 'Headline',
		bio: 'Bio',
		yearsExperience: 'Taon ng karanasan',
		linkedinUrl: 'LinkedIn URL',
		portfolioUrl: 'Portfolio URL',
		resume: 'Resume (PDF o Word)',
		resumeOnFile: 'May naka-file nang resume.',
		saveProfile: 'I-save ang profile',
		savingProfile: 'Sine-save ang profile',
		profileUpdated: 'Na-update ang profile.',
		applicationDetails: 'Detalye ng aplikasyon',
		submitted: 'Naipadala',
		coverLetter: 'Cover letter',
		downloadResume: 'I-download ang resume',
		noResume: 'Walang naka-attach na resume',
		noCoverLetter: 'Walang isinamang cover letter.',
		viewJobPosting: 'Tingnan ang job post',
		appNotFound: 'Hindi nahanap ang aplikasyon.',
		filterApplicants: 'I-filter ang mga aplikante ayon sa status',
		allStatuses: 'Lahat ng status',
		pending: 'Nakabinbin',
		reviewed: 'Nasuri na',
		shortlisted: 'Nasa shortlist',
		rejected: 'Hindi napili',
		hired: 'Natanggap',
		noApplicants: 'Walang aplikanteng tugma sa filter na ito.',
		updateHiringStatus: 'I-update ang hiring status',
		collapseApplicant: 'I-collapse ang detalye ng aplikante',
		expandApplicant: 'I-expand ang detalye ng aplikante',
		nothingHere: 'Walang laman sa address na ito.',
		previous: 'Nakaraan',
		next: 'Susunod',
		pageOf: 'Pahina {current} ng {last}',
		loading: 'Naglo-load...',
		loadingPage: 'Naglo-load ng pahina',
		somethingWrong: 'May nangyaring mali',
		refreshTryAgain: 'I-refresh ang pahina at subukan muli.',
		refreshPage: 'I-refresh ang pahina',
		switchLightTheme: 'Lumipat sa light theme',
		switchDarkTheme: 'Lumipat sa dark theme',
		reviewCandidates:
			'Suriin ang mga kandidato at i-update ang hiring status nila.',
		couldNotLogin: 'Hindi makapag-log in.',
		couldNotCreateAccount: 'Hindi nagawa ang iyong account.',
		couldNotSendReset: 'Hindi maipadala ang reset email.',
		couldNotReset: 'Hindi ma-reset ang iyong password.',
		couldNotUpdateAccount: 'Hindi ma-update ang mga setting ng account.',
		couldNotDeleteAccount: 'Hindi matanggal ang account. Subukan muli.',
		couldNotSubmitApplication: 'Hindi maipadala ang iyong aplikasyon.',
		updateListingDescription:
			'I-update ang listing na makikita ng mga kandidato.',
		savedJobsDescription: 'Mga trabahong nai-bookmark mo para balikan.',
		nothingSaved: 'Wala pang nai-save.',
		couldNotDownloadResume: 'Hindi ma-download ang resume.',
		couldNotSaveProfile: 'Hindi ma-save ang iyong profile.',
		couldNotSaveCompanyProfile: 'Hindi ma-save ang profile ng kumpanya.',
		openToNewRoles: 'Bukas sa mga bagong trabaho',
		skills: 'Mga kasanayan',
		companyFallback: 'Isang kumpanya',
		timeUnits: {
			year: 'taon',
			month: 'buwan',
			week: 'linggo',
			day: 'araw',
			hour: 'oras',
			minute: 'minuto',
			justNow: 'ngayon lang',
			ago: 'ang nakalipas',
		},
		open: 'Bukas',
		draft: 'Draft',
		pendingReview: 'Nakabinbing pagsusuri',
		notSelected: 'Hindi napili',
		servingLocation: 'Para sa Quezon, Palawan',
		homeTitle: 'Hanapin ang tamang trabaho. Kuhanin ang tamang tao.',
		homeDescription:
			'Ikinokonekta ng Servease ang mga tao sa Quezon, Palawan sa lokal na oportunidad at mapagkakatiwalaang kandidato.',
		serviceOrKeyword: 'Serbisyo o keyword',
		location: 'Lokasyon',
		anyType: 'Anumang uri',
		fullTime: 'Full-time',
		partTime: 'Part-time',
		contract: 'Kontrata',
		internship: 'Internship',
		temporary: 'Pansamantala',
		anyMode: 'Anumang paraan',
		onSite: 'On-site',
		remote: 'Remote',
		hybrid: 'Hybrid',
		findJobs: 'Maghanap ng trabaho',
		fetchingListings: 'Kinukuha ang mga listahan...',
		listingsLoadError: 'Hindi ma-load ang mga listahan sa ngayon.',
		noRoles:
			'Wala pang trabahong tugma sa mga filter na iyon. Subukang palawakin ang paghahanap.',
		footer: 'Servease - hanapin ang susunod mong hakbang',
		pageTitles: {
			home: 'Hanapin ang Susunod Mong Trabaho',
			login: 'Maligayang Pagbabalik',
			register: 'Sumali sa Crew',
			forgotPassword: 'Nakalimutan ang Password',
			resetPassword: 'I-reset ang Password',
			dashboard: 'Iyong Workspace',
			postJob: 'Mag-post ng Bagong Oportunidad',
			savedJobs: 'Iyong Nai-save na Trabaho',
			companyProfile: 'Profile ng Kumpanya',
			candidateProfile: 'Profile ng Kandidato',
			jobDetails: 'Detalye ng Trabaho',
			editJob: 'I-edit ang Trabaho',
			applicants: 'Mga Aplikante',
			applicationDetails: 'Detalye ng Aplikasyon',
			pageNotFound: 'Hindi Nahanap ang Pahina',
			page: 'Pahina',
			accountSettings: 'Mga setting ng account',
		},
	},
};

function getInitialLanguage() {
	return localStorage.getItem('servease-language') === 'fil' ? 'fil' : 'en';
}

export function LanguageProvider({ children }) {
	const [language, setLanguageState] = useState(getInitialLanguage);
	const setLanguage = (nextLanguage) => {
		const languageCode = nextLanguage === 'fil' ? 'fil' : 'en';
		localStorage.setItem('servease-language', languageCode);
		setLanguageState(languageCode);
	};

	return (
		<LanguageContext.Provider
			value={{ language, setLanguage, t: translations[language] }}
		>
			{children}
		</LanguageContext.Provider>
	);
}

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (!context) {
		throw new Error('useLanguage must be used within a LanguageProvider');
	}

	return context;
}
